# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.qmd']
  workflow_dispatch:

name: Render quarto

permissions: read-all

jobs:
  render-quatro:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`
          path: . # By default, the current working dir is used i.e `quarto render .`
        env: ${{ toJson(secrets) }}
          
      - name: Commit and Push Changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
          # Add all files starting with 'decoy'
          git add decoy_choices/decoy*
      
          # Commit changes if there are any
          git commit -m 'Updated decoy files' || echo "No changes to commit"
      
          # Push changes
          git push origin || echo "No changes to commit"

