# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['**.qmd']
  workflow_dispatch:

name: Render quarto

permissions: read-all

jobs:
  render-quatro:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Render Quarto Project
        shell: bash
        run: |
          # Find all QMD files in the repository
          find . -name "*.qmd" -type f | while read -r file; do
            echo "Rendering $file"
            quarto render "$file" --to html
          done
        # uses: quarto-dev/quarto-actions/render@v2
        # with:
        #   to: html # If set, it will be equivalent to `quarto render --to html`
        #   path: . # By default, the current working dir is used i.e `quarto render .`
        env: 
          GITHUB_TOKEN: ${{ secrets.github_token }}
          JATOS_TOKEN: ${{ secrets.JATOS_TOKEN }}
          JATOS_DECOY_STUDY_UID: ${{ secrets.JATOS_DECOY_STUDY_UID }}
          JATOS_COLORS_AND_IMAGERY_STUDY_UID: ${{ secrets.JATOS_COLORS_AND_IMAGERY_STUDY_UID }}
          JATOS_OBJ_STUDY_UID: ${{ secrets.JATOS_OBJ_STUDY_UID }}
          JATOS_TOMATO_STUDY_UID: ${{ secrets.JATOS_TOMATO_STUDY_UID }}
          JATOS_TEMP_ATT_STUDY_UID: ${{ secrets.JATOS_TEMP_ATT_STUDY_UID }}
          JATOS_MONSTERS_STUDY_UID: ${{ secrets.JATOS_MONSTERS_STUDY_UID }}
          
      - name: Commit and Push Changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
          # Add all necessary files
          git add *.csv
          git add *.html
      
          # Commit changes if there are any
          git commit -m 'Rendered markdown files' || echo "No changes to commit"
      
          # Push changes
          git push origin || echo "No changes to commit"

